spring:
  application:
    name: facebook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: ${JWT_SIGNER_KEY}
  expiration: 3600 # 30 phút
  refresh-expiration: 604800 # 7 ngày
api:
  prefix: /api/v1
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${BREVO_API_KEY}
